src/src/Controller/BaseController.php
<?php

namespace App\Controller;

use App\Entity\User\UserProfile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

abstract class BaseController extends AbstractController
{
    protected function getUser(): UserProfile
    {
        return parent::getUser();
    }
}

src/templates/header/header.html.twig
{% block header %}
<div class="w-100">
  <nav id="header-galaxy" class="navbar navbar-expand-lg pr-">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if app.request.get('_route') == 'index' %} class="active"{% endif %}">
          <a class="nav-link" href="{{ path('index') }}">Home <span
              class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Admin
          </a>
          {% if is_granted('ROLE_ADMIN') %}
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ path('articulos_articles_index') }}">Articulos</a>
            <a class="dropdown-item" href="{{ path('articulos_categories_index')}}">Categories</a>
  
           
 
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ path('user_user_profile_index')}}">UserProfile</a>
            <a class="dropdown-item" href="{{ path('user_user_roles_index')}}">Roles</a>
          </div>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if app.user %}
          <button class="btn btn-outline-light" href="#">

            {{ app.user.username|capitalize }}

          </button>
          {% endif %}
        </li>
      </ul>

      {% if app.user  %}

      <ul class="navbar-nav p-2">
        <li class="nav-item dropdown text-center">
          <a class="nav-link dropdown-toggle bg-dark p-0 rounded-circle border  border-dark" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <img src="{{ app.user.avatarUrl(100) }}" width="70" height="70">
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Dashboard</a>
            <a class="dropdown-item" href="{{ path('app_account') }}">See Profile</a>
            <a class="dropdown-item" href="{{ path('app_logout')}}">Log Out</a>
          </div>
        </li>
      </ul>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <a class="btn btn-outline-light my-2 my-sm-0" href="{{ path('app_login') }}" type="submit">Search</a>
      </form>

      {% else %}
      {% if app.request.get('_route') != 'app_login' %}
          <a class="btn btn-outline-warning my-2 my-sm-0" href="{{ path('app_login') }}" type="submit">Login</a>
      {% endif %}   

      {% endif %}
    </div>
  </nav>
</div>

{% endblock %}